name: face_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.2+2

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  icons_plus: ^5.0.0
  intl: ^0.20.2
  mockito: ^5.5.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  assets:
    - ./assets/
